### ISSUE TITLE
Impossible to connect with built-in Windows files

### ISSUE THREAD

**Issue by maxlerebourg** [117503445/GoWebDAV#9]
I tried your image docker to have a very lightweight webdav server in docker.
But impossible to connect with Windows with localhost and on an external vps.

**Comment by 117503445** [comment]
Sorry, I didn't understand what you meant. Please provide more detailed information so that I can reproduce and resolve the problem.

What is the docker command you are running?
On which OS are you running it?
Can you successfully access the target http port? (You can open other services on that port to verify the connection)

**Comment by maxlerebourg** [comment]
This link explain exactly what i'm trying to do:
https://www.maketecheasier.com/map-webdav-drive-windows10/
In localhost, windows prompt again and again each time I submit valid credentials for a username/password and when I submit a wrong credentials, it said "Impossible to connect".
On ubuntu VPS, behind traefik proxy, it ask for username/password but always "Impossible to connect".

Do you have a working webdav lightweight client I could test ?

**Comment by 117503445** [comment]
You can simply use your browser to access the http port, and you should see a lightweight js-based client.

![example](https://user-images.githubusercontent.com/21152034/187010227-cd6a8ae6-e0d1-4528-9b50-8efaa20b4875.png)

On the other hand, you can disable http basic auth for debugging purposes by setting the username and password to null, null.
